# default rules
corp:
  url:   /corp
  param: { module: corp , action: index }

home:
  url:   /home
  param: { module: home , action: index }

homepage:
  url:   /
  param: { module: corp, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

home:
  url:   /home
  param: { module: home , action: index }

tour:
  url:   /tour
  param: { module: tour , action: tour }

shows:
  url:   /shows
  param: { module: browse , action: defBrowse }


browse:
  url:   /browse
  param: { module: browse , action: browse2 }

contribute:
  url:   /contribute
  param: { module: contribute , action: defContribute }

edit:
  url:   /edit
  param: { module: edit , action: defEdit }

emailImport:
  url:   /emailImport
  param: { module: emailImport , action: defEmailImport }

vshowcss:
  url:   /vshowcss
  param: { module: vshowcss , action: defVshowcss }

flvprovider:
  url:   /flv/:file_info
  param: { module: veditorservices , action: flvprovider }

veditorservices:
  url:   /veditorservices
  param: { module: veditorservices , action: defVeditorservices }

login:
  url:   /login
  param: { module: login , action: signin }

mail:
  url:   /mail
  param: { module: mail , action: defMail }

myvidiun:
  url:   /myvidiun
  param: { module: myvidiun , action: defMyvidiun }

produce:
  url:   /produce
  param: { module: produce , action: defProduce }

search:
  url:   /search
  param: { module: search , action: defSearch }

 #sns:
 #  url:   /sns
 #  param: { module: sns , action: defSns }

static:
  url:   /static
  param: { module: static , action: defStatic }

help:
  url:   /help
  param: { module: forum , action: defForum }

system:
  url:   /system
  param: { module: system , action: defSystem }

upload:
  url:   /upload
  param: { module: upload , action: defUpload }

view:
  url:   /view
  param: { module: view , action: defView }

widget:
  url:  /widget/:vshow_id/:entry_id/:vmedia_type
  param: { module: browse , action: widget }

widget2:
  url:  /widget/:vshow_id/:entry_id/:vmedia_type/:widget_type
  param: { module: browse , action: widget }

widget3:
  url:  /widget/:vshow_id/:entry_id/:vmedia_type/:widget_type/:version
  param: { module: browse , action: widget }

widget4:
  url:  /widget/:vshow_id/:entry_id/:vmedia_type/:widget_type/:version/:vdata
  param: { module: browse , action: widget }

vwidgetThumbail:
  url:  /vwidget/thumbnail/:wid
  param: { module: extwidget, action: getWidgetThumbnail }

vwidget:
  url:  /vwidget/*
  param: { module: extwidget , action: vwidget }

forum:
  url:   /forum
  param: { module: forum , action: defForum }

extservices:
  url:   /extservices
  param: { module: extservices , action: defExtservices }

partnerservices:
  url:   /partnerservices
  param: { module: partnerservices , action: defPartnerservices }

partnerservices2testme:
  url:   /partnerservices2/testme
  param: { module: partnerservices2 , action: testme }

partnerservices2:
  url:   /partnerservices2/:myaction
  param: { module: partnerservices2 , action: defPartnerservices2base }

cms_player_widget:
  url: /cms/playerWidget/:vshow_id/:entry_id
  param: { module: cms, action: playerWidget }

cms:
  url:   /cms
  param: { module: cms , action: signup }

vmc:
  url:   /vmc
  param: { module: vmc , action: vmc }

vmcng:
  url:   /vmcng
  param: { module: vmcng , action: vmcng }

vmcng_reset_password:
    url:   /vmcng/resetpassword/*
    param: { module: vmcng , action: resetpassword }

vmcng_default:
  url:   /vmcng/*
  param: { module: vmcng , action: vmcng }

default_index:
  url:   /:module
  param: { action: index }


default:
  url:   /:module/:action/*


