default:
  has_layout:   on
  layout:       vmclayout
  javascripts:  [ -* ]
  stylesheets:  [ /lib/css/modal, /lib/css/vmc ]

vmcSuccess: 
  has_layout:   on
  layout:       vmclayout
  javascripts:  [ -* ]
  stylesheets:  [ /lib/css/vmc ]

vmc1Success:
  has_layout:     on
  layout:         vmc1layout
  javascripts:    [ -*, /lib/js/jquery-1.3.1.min.js, /lib/js/vmc1modal , /lib/js/common , /lib/js/functions.js , http://ajax.googleapis.com/ajax/libs/swfobject/2.1/swfobject.js ]
  stylesheets:  [ -*, /lib/css/vmc1modal, /lib/css/vmc1 ]

vmc4Success:
  has_layout:     on
  layout:       vmclayout
  javascripts:  [ -* ]
  stylesheets:  [ -*, /lib/css/vmc5 ]

varpartnerlistSuccess:
  has_layout:     on
  layout:         vmc1layout
  javascripts:    [ -*, /lib/js/vmc1modal , /lib/js/common , /lib/js/functions.js , http://ajax.googleapis.com/ajax/libs/swfobject/2.1/swfobject.js ]
  stylesheets:  [ -*, /lib/css/vmc1modal, /lib/css/vmc1 ]

supportSuccess:
  has_layout:     off
  layout:         vmc1layout
  javascripts:    [ -* ]
  stylesheets:    [ -* ]

updateLoginDataSuccess:
  has_layout:     off
  javascripts:    [ -* ]
  stylesheets:    [ -* ]

helpSuccess:
  has_layout:     on
  layout:         helplayout
  javascripts:    [ -* ]
  stylesheets:    [ -*, /lib/css/vmc ]

vmc2helpSuccess:
  has_layout:     on
  layout:         helplayout
  javascripts:    [ -*, /lib/js/jquery.v1.4.2.min.js ]
  stylesheets:    [ -*, /lib/css/vmc ]

previewSuccess:
  has_layout:     off
  layout:         helplayout
  javascripts:    [ -* ]
  stylesheets:    [ -*, /lib/css/vmc ]