
<script type="text/javascript">

<?php require_once __DIR__ . '/js/vObjects.js'; ?>


function getVariables(vSelection, value, variables) {

	var variable =  'value';
	if(vSelection.variable)
		variable = vSelection.variable;

	variables[variable] = value;
	
	for(var variable in vSelection)
		variables[variable] = vSelection[variable];
	
	return variables;
}

function addSelections(label, vSelections, selectCallback) {
	var jqSelection = jQuery('<select><option value="">' + label + '</option></select>');
	var jqWrap = null;
	
	for(var value in vSelections){
		var vSelection = vSelections[value];
		jqSelection.append('<option value="' + value + '">' + vSelection.label + '</option>');
	}

	jqSelection.change(function(){

		if(jqWrap){
			jqWrap.empty();
		}
		else{
			jqWrap = jQuery('<div/>');
			jqSelection.after(jqWrap);
		}

		var value =  jqSelection.val();
		var vSelection = vSelections[value];
		if(vSelection != null && vSelection.subSelections == null && vSelection.fieldType == null){

			var variablesObject = getVariables(vSelection, value, {});
			selectCallback.apply(jqSelection, [null, variablesObject]);
			return;
		}

		var jqSubField = null;
		switch(vSelection.fieldType)
		{
			case 'text':
				jqSubField = jQuery('<input>');
				jqSubField.keyup(function(){
					selectCallback.apply(jqSelection, [null, {value: "'" + jqSubField.val() + "'"}]);
				});
				break;
	
			case 'checkbox':
				jqSubField = jQuery('<input type="checkbox">');
				jqSubField.change(function(){
					selectCallback.apply(jqSelection, [null, {value: (jqSubField.attr('checked') ? 'true' : 'false')}]);
				});
				break;
			
			default:
				jqSubField = addSelections(vSelection.subLabel, vSelection.subSelections, function(subData, variables){
					variables = getVariables(vSelection, jqSubField.val(), variables);
		
					var data = subData;
					if(vSelection.getData)
						var data = vSelection.getData.apply(jqSelection, [subData, variables]);
					
					selectCallback.apply(jqSelection, [data, variables]);
				});
		}
		jqWrap.append(jqSubField);
	});
	
	return jqSelection;
};

jQuery(document).ready(function() {
	jQuery('#dataType').change(function(){

		jQuery('#frmObject').hide();
		jQuery('#frmFreeText').hide();
		
		switch(jQuery(this).val()){
			case 'object':
				jQuery('#frmObject').show();
				break;

			case 'text':
				jQuery('#frmFreeText').show();
			case 'map':
				break;
		}
	});
	jQuery('#dataType').change();

	var jqObject = jQuery('#object');
	var jqObjectApiName = jQuery('#objectType');
	
	var jqSelection = addSelections('Select Object', vObjects, function(data, variables){
		jqObject.val(data.code);
		jqObjectApiName.val(data.apiName);
	});
	jqObject.before(jqSelection);
});


</script>