<?php 
	$this->headScript()	->setIndent("	")
						->appendFile($this->baseUrl('js/swfobject.js'));
?>

<div id="vcwEditor"></div>
<script type="text/javascript">
	var flashvars = {
		baseXmlUrl: "<?php echo $this->vcwBaseUrl . $this->vcwEditorVersion ?>/assets/base.xml"
	};
	var params = {};
	params.quality = "high";
	params.bgcolor = "#ffffff";
	params.allowscriptaccess = "sameDomain";
	params.allowfullscreen = "true";
	var attributes = {};
	attributes.id = "VCWEditor";
	attributes.name = "VCWEditor";
	attributes.align = "middle";

	swfobject.embedSWF("<?php echo $this->vcwBaseUrl . $this->vcwEditorVersion ?>/VCWEditor.swf", "vcwEditor", "100%", "100%", "9.0", false, flashvars, params, attributes);
	var confFile = "";
	var shouldSave = false;
	  	
	function VCWEditor_ReadyHandler() {
		var confFile = window.parent.jQuery('#conf_file').val();
		if (jQuery.trim(confFile).length > 0) {
			var f = document.getElementById("VCWEditor");
			f.setConfXML(confFile);
		}
	}
	
	function VCWEditor_publishXML(xml) {
		confFile = unescape(xml);
		shouldSave = true;
	}
	
	function VCWEditor_close() {
		if (shouldSave)
			window.parent.jQuery('#conf_file').val(confFile);
			
		window.parent.jQuery('#vcw-editor').dialog('close');
	}	
</script>