<?php
// This file generated by Propel  convert-conf target
// from XML runtime conf file C:\opt\vidiun\app\alpha\config\runtime-conf.xml
return array (
  'datasources' => 
  array (
    'vidiun' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'phptype' => 'mysql',
        'database' => 'vidiun',
        'hostspec' => 'localhost',
        'username' => 'root',
        'password' => 'root',
      ),
    ),
    'default' => 'vidiun',
  ),
  'log' => 
  array (
    'ident' => 'vidiun',
    'level' => '7',
  ),
  'generator_version' => '1.4.2',
  'classmap' => 
  array (
    'AuditTrailTableMap' => 'lib/model/map/AuditTrailTableMap.php',
    'AuditTrailPeer' => 'lib/model/AuditTrailPeer.php',
    'AuditTrail' => 'lib/model/AuditTrail.php',
    'AuditTrailDataTableMap' => 'lib/model/map/AuditTrailDataTableMap.php',
    'AuditTrailDataPeer' => 'lib/model/AuditTrailDataPeer.php',
    'AuditTrailData' => 'lib/model/AuditTrailData.php',
    'AuditTrailConfigTableMap' => 'lib/model/map/AuditTrailConfigTableMap.php',
    'AuditTrailConfigPeer' => 'lib/model/AuditTrailConfigPeer.php',
    'AuditTrailConfig' => 'lib/model/AuditTrailConfig.php',
  ),
);