<?php
// This file generated by Propel  convert-conf target
// from XML runtime conf file /opt/vidiun/app/alpha/config/runtime-conf.xml
return array (
  'datasources' => 
  array (
    'vidiun' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'phptype' => 'mysql',
        'database' => 'vidiun',
        'hostspec' => 'localhost',
        'username' => 'root',
        'password' => 'root',
      ),
    ),
    'default' => 'vidiun',
  ),
  'log' => 
  array (
    'ident' => 'vidiun',
    'level' => '7',
  ),
  'generator_version' => '1.4.2',
  'classmap' => 
  array (
    'VendorCatalogItemTableMap' => 'lib/model/map/VendorCatalogItemTableMap.php',
    'VendorCatalogItemPeer' => 'lib/model/VendorCatalogItemPeer.php',
    'VendorCatalogItem' => 'lib/model/VendorCatalogItem.php',
    'PartnerCatalogItemTableMap' => 'lib/model/map/PartnerCatalogItemTableMap.php',
    'PartnerCatalogItemPeer' => 'lib/model/PartnerCatalogItemPeer.php',
    'PartnerCatalogItem' => 'lib/model/PartnerCatalogItem.php',
    'ReachProfileTableMap' => 'lib/model/map/ReachProfileTableMap.php',
    'ReachProfilePeer' => 'lib/model/ReachProfilePeer.php',
    'ReachProfile' => 'lib/model/ReachProfile.php',
    'EntryVendorTaskTableMap' => 'lib/model/map/EntryVendorTaskTableMap.php',
    'EntryVendorTaskPeer' => 'lib/model/EntryVendorTaskPeer.php',
    'EntryVendorTask' => 'lib/model/EntryVendorTask.php',
  ),
);